name: Purge GitHub Camo Cache

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  purge-camo-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Purge GitHub Camo Cache
        uses: kevincobain2000/action-camo-purge@v1
